#!/usr/bin/env bash
# PostToolUse hook: regenerate the treetop parser (.rb) for an edited .treetop file.
# Generated parsers are gitignored, so tests would silently run against stale code otherwise.
set -u

input=$(cat)
if command -v jq >/dev/null 2>&1; then
  file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
else
  file=$(printf '%s' "$input" | sed -n 's/.*"file_path":[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
fi

case "$file" in
  *.treetop) ;;
  *) exit 0 ;;
esac

case "$file" in
  */grammar/reserved_word.treetop)
    echo "reserved_word.treetop is generated by reserved_word_generator.rb; edit the generator and run 'bundle exec rake gen_force' instead." >&2
    exit 2
    ;;
esac

cd "${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel)}" || exit 0
output="${file%.treetop}.rb"

out=$(bundle exec tt "$file" -f -o "$output" 2>&1)
status=$?
printf '%s\n' "$out" | grep -v -E 'warning: mismatched indentations|^[[:space:]]+from ' | sed '/^$/d'

if [ "$status" -ne 0 ]; then
  echo "tt failed for $file; fix the grammar before running tests." >&2
  exit 2
fi
echo "regenerated $output"
