changelog:
  exclude:
    labels:
      - release
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: New Features
      labels:
        - enhancement
    - title: Improvements
      labels:
        - improvement
    - title: Bug Fixes
      labels:
        - bug
    - title: Security
      labels:
        - security
    - title: Dependencies
      labels:
        - dependencies
    - title: CI
      labels:
        - github_actions
    - title: Housekeeping
      labels:
        - housekeeping
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
