language: ruby
rvm:
  - 1.9.3
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1
sudo: required
before_install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - gem install bundler -v 1.12.5
script:
  - rake gen_force
  - rake test
