language: ruby
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
# - 3.0.0
sudo: required
env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE ORACLE_USERNAME=travis ORACLE_PASSWORD=travis ORACLE_HOST=localhost  ORACLE_PORT=1521

before_install:
  # https://github.com/Vincit/travis-oracledb-xe
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - gem update --system
  - gem install bundler -v 2.0.0

script:
  - bundle exec rake gen_force
  - bundle exec rake test
