module SqlParser
  class OracleReservedWords
    def self.plural_words
      {
        'IS\s+NULL' => 'IS_NULL',
        'IS\s+NOT\s+NULL' => 'IS_NOT_NULL',
        'NOT\s+LIKE' => 'NOT_LIKE',
        'NOT\s+BETWEEN' => 'NOT_BETWEEN',
        'NOT\s+IN' => 'NOT_IN',
      }
    end

    def self.single_words
      {
        'ACCESS' => 'ACCESS',
        'ADD' => 'ADD',
        'ALL' => 'ALL',
        'ALTER' => 'ALTER',
        'AND' => 'AND',
        'ANY' => 'ANY',
        'AS' => 'AS',
        'ASC' => 'ASC',
        'AUDIT' => 'AUDIT',
        'BETWEEN' => 'BETWEEN',
        'BY' => 'BY',
        'CHAR' => 'CHAR',
        'CHECK' => 'CHECK',
        'CLUSTER' => 'CLUSTER',
        'COLUMN' => 'COLUMN',
        'COLUMN_VALUE' => 'COLUMN_VALUE',
        'COMMENT' => 'COMMENT',
        'COMPRESS' => 'COMPRESS',
        'CONNECT' => 'CONNECT',
        'CREATE' => 'CREATE',
        'CURRENT' => 'CURRENT',
        'DATE' => 'DATE',
        'DECIMAL' => 'DECIMAL',
        'DEFAULT' => 'DEFAULT',
        'DELETE' => 'DELETE',
        'DESC' => 'DESC',
        'DISTINCT' => 'DISTINCT',
        'DROP' => 'DROP',
        'ELSE' => 'ELSE',
        'ESCAPE' => 'ESCAPE',
        'EXCLUSIVE' => 'EXCLUSIVE',
        'EXISTS' => 'EXISTS',
        'FILE' => 'FILE',
        'FLOAT' => 'FLOAT',
        'FOR' => 'FOR',
        'FROM' => 'FROM',
        'GRANT' => 'GRANT',
        'GROUP' => 'GROUP',
        'HAVING' => 'HAVING',
        'IDENTIFIED' => 'IDENTIFIED',
        'IMMEDIATE' => 'IMMEDIATE',
        'IN' => 'IN',
        'INCREMENT' => 'INCREMENT',
        'INDEX' => 'INDEX',
        'INITIAL' => 'INITIAL',
        'INSERT' => 'INSERT',
        'INTEGER' => 'INTEGER',
        'INTERSECT' => 'INTERSECT',
        'INTO' => 'INTO',
        'IS' => 'IS',
        'LEVEL' => 'LEVEL',
        'LIKE' => 'LIKE',
        'LIKEC' => 'LIKEC',
        'LIKE2' => 'LIKE2',
        'LIKE4' => 'LIKE4',
        'LOCK' => 'LOCK',
        'LONG' => 'LONG',
        'MAXEXTENTS' => 'MAXEXTENTS',
        'MINUS' => 'MINUS',
        'MLSLABEL' => 'MLSLABEL',
        'MODE' => 'MODE',
        'MODIFY' => 'MODIFY',
        'NESTED_TABLE_ID' => 'NESTED_TABLE_ID',
        'NOAUDIT' => 'NOAUDIT',
        'NOCOMPRESS' => 'NOCOMPRESS',
        'NOT' => 'NOT',
        'NOWAIT' => 'NOWAIT',
        'NULL' => 'NULL',
        'NUMBER' => 'NUMBER',
        'OF' => 'OF',
        'OFFLINE' => 'OFFLINE',
        'ON' => 'ON',
        'ONLINE' => 'ONLINE',
        'OPTION' => 'OPTION',
        'OR' => 'OR',
        'ORDER' => 'ORDER',
        'PCTFREE' => 'PCTFREE',
        'PRIOR' => 'PRIOR',
        'PRIVILEGES' => 'PRIVILEGES',
        'PUBLIC' => 'PUBLIC',
        'RAW' => 'RAW',
        'REGEXP_LIKE' => 'REGEXP_LIKE',
        'RENAME' => 'RENAME',
        'RESOURCE' => 'RESOURCE',
        'REVOKE' => 'REVOKE',
        'ROW' => 'ROW',
        'ROWID' => 'ROWID',
        'ROWNUM' => 'ROWNUM',
        'ROWS' => 'ROWS',
        'SELECT' => 'SELECT',
        'SESSION' => 'SESSION',
        'SET' => 'SET',
        'SHARE' => 'SHARE',
        'SIZE' => 'SIZE',
        'SMALLINT' => 'SMALLINT',
        'START' => 'START',
        'SUCCESSFUL' => 'SUCCESSFUL',
        'SYNONYM' => 'SYNONYM',
        'SYSDATE' => 'SYSDATE',
        'TABLE' => 'TABLE',
        'THEN' => 'THEN',
        'TO' => 'TO',
        'TRIGGER' => 'TRIGGER',
        'UID' => 'UID',
        'UNION' => 'UNION',
        'UNIQUE' => 'UNIQUE',
        'UPDATE' => 'UPDATE',
        'USER' => 'USER',
        'VALIDATE' => 'VALIDATE',
        'VALUES' => 'VALUES',
        'VARCHAR' => 'VARCHAR',
        'VARCHAR2' => 'VARCHAR2',
        'VIEW' => 'VIEW',
        'WHENEVER' => 'WHENEVER',
        'WHERE' => 'WHERE',
      }
    end
  end
end
