# Autogenerated from a Treetop grammar. Edits may be lost.


module OracleSqlParser::Grammar::Condition
  module Between
    include Treetop::Runtime

    def root
      @root ||= :between_condition
    end

    module BetweenCondition0
      def not_keyword
        elements[0]
      end

      def space
        elements[1]
      end
    end

    module BetweenCondition1
      def target
        elements[0]
      end

      def space1
        elements[1]
      end

      def n
        elements[2]
      end

      def between_keyword
        elements[3]
      end

      def space2
        elements[4]
      end

      def from
        elements[5]
      end

      def space3
        elements[6]
      end

      def and_keyword
        elements[7]
      end

      def space4
        elements[8]
      end

      def to
        elements[9]
      end
    end

    module BetweenCondition2
      def ast
        OracleSqlParser::Ast::BetweenCondition[
          :target => target.ast,
          :not => not_keyword.ast,
          :from => from.ast,
          :to => to.ast
        ]
      end

      def not_keyword
        n.elements && n.elements.first
      end
    end

    def _nt_between_condition
      start_index = index
      if node_cache[:between_condition].has_key?(index)
        cached = node_cache[:between_condition][index]
        if cached
          node_cache[:between_condition][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_expr
      s0 << r1
      if r1
        r2 = _nt_space
        s0 << r2
        if r2
          i4, s4 = index, []
          r5 = _nt_not_keyword
          s4 << r5
          if r5
            r6 = _nt_space
            s4 << r6
          end
          if s4.last
            r4 = instantiate_node(SyntaxNode,input, i4...index, s4)
            r4.extend(BetweenCondition0)
          else
            @index = i4
            r4 = nil
          end
          if r4
            r3 = r4
          else
            r3 = instantiate_node(SyntaxNode,input, index...index)
          end
          s0 << r3
          if r3
            r7 = _nt_between_keyword
            s0 << r7
            if r7
              r8 = _nt_space
              s0 << r8
              if r8
                r9 = _nt_expr
                s0 << r9
                if r9
                  r10 = _nt_space
                  s0 << r10
                  if r10
                    r11 = _nt_and_keyword
                    s0 << r11
                    if r11
                      r12 = _nt_space
                      s0 << r12
                      if r12
                        r13 = _nt_expr
                        s0 << r13
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(BetweenCondition1)
        r0.extend(BetweenCondition2)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:between_condition][start_index] = r0

      r0
    end


    class Parser < Treetop::Runtime::CompiledParser
      include Between
    end
  end

  (remove_const(:BetweenParser) if const_defined?(:BetweenParser)) rescue nil; BetweenParser = Between::Parser

end
