# Autogenerated from a Treetop grammar. Edits may be lost.


module OracleSqlParser::Grammar::Condition
  module Compound
    include Treetop::Runtime

    def root
      @root ||= :compound_condition
    end

    module CompoundCondition0
      def logical_condition
        elements[1]
      end

    end

    module CompoundCondition1
      def ast
        OracleSqlParser::Ast::CompoundCondition[:condition => logical_condition.ast]
      end
    end

    def _nt_compound_condition
      start_index = index
      if node_cache[:compound_condition].has_key?(index)
        cached = node_cache[:compound_condition][index]
        if cached
          node_cache[:compound_condition][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      if (match_len = has_terminal?('(', false, index))
        r1 = true
        @index += match_len
      else
        terminal_parse_failure('\'(\'')
        r1 = nil
      end
      s0 << r1
      if r1
        r2 = _nt_logical_condition
        s0 << r2
        if r2
          if (match_len = has_terminal?(')', false, index))
            r3 = true
            @index += match_len
          else
            terminal_parse_failure('\')\'')
            r3 = nil
          end
          s0 << r3
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(CompoundCondition0)
        r0.extend(CompoundCondition1)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:compound_condition][start_index] = r0

      r0
    end


    class Parser < Treetop::Runtime::CompiledParser
      include Compound
    end
  end

  (remove_const(:CompoundParser) if const_defined?(:CompoundParser)) rescue nil; CompoundParser = Compound::Parser

end
