# Autogenerated from a Treetop grammar. Edits may be lost.


module OracleSqlParser::Grammar::Condition
  module Exists
    include Treetop::Runtime

    def root
      @root ||= :exists_condition
    end

    module ExistsCondition0
      def exists_keyword
        elements[0]
      end

      def subquery
        elements[4]
      end

    end

    module ExistsCondition1
      def ast
        OracleSqlParser::Ast::ExistsCondition[
          :target => subquery.ast
        ]
      end
    end

    def _nt_exists_condition
      start_index = index
      if node_cache[:exists_condition].has_key?(index)
        cached = node_cache[:exists_condition][index]
        if cached
          node_cache[:exists_condition][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_exists_keyword
      s0 << r1
      if r1
        r3 = _nt_space
        if r3
          r2 = r3
        else
          r2 = instantiate_node(SyntaxNode,input, index...index)
        end
        s0 << r2
        if r2
          if (match_len = has_terminal?('(', false, index))
            r4 = true
            @index += match_len
          else
            terminal_parse_failure('\'(\'')
            r4 = nil
          end
          s0 << r4
          if r4
            r6 = _nt_space
            if r6
              r5 = r6
            else
              r5 = instantiate_node(SyntaxNode,input, index...index)
            end
            s0 << r5
            if r5
              r7 = _nt_subquery
              s0 << r7
              if r7
                r9 = _nt_space
                if r9
                  r8 = r9
                else
                  r8 = instantiate_node(SyntaxNode,input, index...index)
                end
                s0 << r8
                if r8
                  if (match_len = has_terminal?(')', false, index))
                    r10 = true
                    @index += match_len
                  else
                    terminal_parse_failure('\')\'')
                    r10 = nil
                  end
                  s0 << r10
                end
              end
            end
          end
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(ExistsCondition0)
        r0.extend(ExistsCondition1)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:exists_condition][start_index] = r0

      r0
    end


    class Parser < Treetop::Runtime::CompiledParser
      include Exists
    end
  end

  (remove_const(:ExistsParser) if const_defined?(:ExistsParser)) rescue nil; ExistsParser = Exists::Parser

end
