# Autogenerated from a Treetop grammar. Edits may be lost.


module OracleSqlParser::Grammar::Condition
  module FloatingPoint
    include Treetop::Runtime

    def root
      @root ||= :floating_point_condition
    end

    module FloatingPointCondition0
      def expr
        elements[0]
      end

      def is_keyword
        elements[2]
      end

      def not_keyword
        elements[4]
      end

      def value
        elements[6]
      end
    end

    module FloatingPointCondition1
      def ast
        OracleSqlParser::Ast::FloatingPointCondition[
          :target => expr.ast,
          :is => is_keyword.ast,
          :not => not_keyword.ast,
          :value => value.ast
        ]
      end
    end

    def _nt_floating_point_condition
      start_index = index
      if node_cache[:floating_point_condition].has_key?(index)
        cached = node_cache[:floating_point_condition][index]
        if cached
          node_cache[:floating_point_condition][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_expr
      s0 << r1
      if r1
        r3 = _nt_space
        if r3
          r2 = r3
        else
          r2 = instantiate_node(SyntaxNode,input, index...index)
        end
        s0 << r2
        if r2
          r4 = _nt_is_keyword
          s0 << r4
          if r4
            r6 = _nt_space
            if r6
              r5 = r6
            else
              r5 = instantiate_node(SyntaxNode,input, index...index)
            end
            s0 << r5
            if r5
              r8 = _nt_not_keyword
              if r8
                r7 = r8
              else
                r7 = instantiate_node(SyntaxNode,input, index...index)
              end
              s0 << r7
              if r7
                r10 = _nt_space
                if r10
                  r9 = r10
                else
                  r9 = instantiate_node(SyntaxNode,input, index...index)
                end
                s0 << r9
                if r9
                  i11 = index
                  r12 = _nt_nan_keyword
                  if r12
                    r12 = SyntaxNode.new(input, (index-1)...index) if r12 == true
                    r11 = r12
                  else
                    r13 = _nt_infinite_keyword
                    if r13
                      r13 = SyntaxNode.new(input, (index-1)...index) if r13 == true
                      r11 = r13
                    else
                      @index = i11
                      r11 = nil
                    end
                  end
                  s0 << r11
                end
              end
            end
          end
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(FloatingPointCondition0)
        r0.extend(FloatingPointCondition1)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:floating_point_condition][start_index] = r0

      r0
    end


    class Parser < Treetop::Runtime::CompiledParser
      include FloatingPoint
    end
  end

  (remove_const(:FloatingPointParser) if const_defined?(:FloatingPointParser)) rescue nil; FloatingPointParser = FloatingPoint::Parser

end
