# Autogenerated from a Treetop grammar. Edits may be lost.


module OracleSqlParser::Grammar::Condition
  module In
    include Treetop::Runtime

    def root
      @root ||= :in_condition
    end

    module InCondition0
      def not_keyword
        elements[0]
      end

      def space
        elements[1]
      end
    end

    module InCondition1
      def target
        elements[0]
      end

      def space
        elements[1]
      end

      def n
        elements[2]
      end

      def in_keyword
        elements[3]
      end

      def values
        elements[7]
      end

    end

    module InCondition2
      def ast
        OracleSqlParser::Ast::InCondition[
          :target => target.ast,
          :not => not_keyword.ast,
          :values =>  values.ast
        ]
      end

      def not_keyword
        n.elements && n.elements.first
      end
    end

    def _nt_in_condition
      start_index = index
      if node_cache[:in_condition].has_key?(index)
        cached = node_cache[:in_condition][index]
        if cached
          node_cache[:in_condition][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_expr
      s0 << r1
      if r1
        r2 = _nt_space
        s0 << r2
        if r2
          i4, s4 = index, []
          r5 = _nt_not_keyword
          s4 << r5
          if r5
            r6 = _nt_space
            s4 << r6
          end
          if s4.last
            r4 = instantiate_node(SyntaxNode,input, i4...index, s4)
            r4.extend(InCondition0)
          else
            @index = i4
            r4 = nil
          end
          if r4
            r3 = r4
          else
            r3 = instantiate_node(SyntaxNode,input, index...index)
          end
          s0 << r3
          if r3
            r7 = _nt_in_keyword
            s0 << r7
            if r7
              r9 = _nt_space
              if r9
                r8 = r9
              else
                r8 = instantiate_node(SyntaxNode,input, index...index)
              end
              s0 << r8
              if r8
                if (match_len = has_terminal?('(', false, index))
                  r10 = true
                  @index += match_len
                else
                  terminal_parse_failure('\'(\'')
                  r10 = nil
                end
                s0 << r10
                if r10
                  r12 = _nt_space
                  if r12
                    r11 = r12
                  else
                    r11 = instantiate_node(SyntaxNode,input, index...index)
                  end
                  s0 << r11
                  if r11
                    i13 = index
                    r14 = _nt_exprs
                    if r14
                      r14 = SyntaxNode.new(input, (index-1)...index) if r14 == true
                      r13 = r14
                    else
                      r15 = _nt_subquery
                      if r15
                        r15 = SyntaxNode.new(input, (index-1)...index) if r15 == true
                        r13 = r15
                      else
                        @index = i13
                        r13 = nil
                      end
                    end
                    s0 << r13
                    if r13
                      r17 = _nt_space
                      if r17
                        r16 = r17
                      else
                        r16 = instantiate_node(SyntaxNode,input, index...index)
                      end
                      s0 << r16
                      if r16
                        if (match_len = has_terminal?(')', false, index))
                          r18 = true
                          @index += match_len
                        else
                          terminal_parse_failure('\')\'')
                          r18 = nil
                        end
                        s0 << r18
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(InCondition1)
        r0.extend(InCondition2)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:in_condition][start_index] = r0

      r0
    end


    class Parser < Treetop::Runtime::CompiledParser
      include In
    end
  end

  (remove_const(:InParser) if const_defined?(:InParser)) rescue nil; InParser = In::Parser

end
