# Autogenerated from a Treetop grammar. Edits may be lost.


module OracleSqlParser::Grammar::Condition
  module Null
    include Treetop::Runtime

    def root
      @root ||= :null_condition
    end

    module NullCondition0
      def not_keyword
        elements[0]
      end

      def space
        elements[1]
      end
    end

    module NullCondition1
      def expr
        elements[0]
      end

      def space1
        elements[1]
      end

      def is_keyword
        elements[2]
      end

      def space2
        elements[3]
      end

      def n
        elements[4]
      end

      def null_keyword
        elements[5]
      end
    end

    module NullCondition2
      def ast
        OracleSqlParser::Ast::NullCondition[
          :target => expr.ast,
          :not => not_keyword.ast]
      end

      def not_keyword
        n.elements && n.elements.first
      end
    end

    def _nt_null_condition
      start_index = index
      if node_cache[:null_condition].has_key?(index)
        cached = node_cache[:null_condition][index]
        if cached
          node_cache[:null_condition][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_expr
      s0 << r1
      if r1
        r2 = _nt_space
        s0 << r2
        if r2
          r3 = _nt_is_keyword
          s0 << r3
          if r3
            r4 = _nt_space
            s0 << r4
            if r4
              i6, s6 = index, []
              r7 = _nt_not_keyword
              s6 << r7
              if r7
                r8 = _nt_space
                s6 << r8
              end
              if s6.last
                r6 = instantiate_node(SyntaxNode,input, i6...index, s6)
                r6.extend(NullCondition0)
              else
                @index = i6
                r6 = nil
              end
              if r6
                r5 = r6
              else
                r5 = instantiate_node(SyntaxNode,input, index...index)
              end
              s0 << r5
              if r5
                r9 = _nt_null_keyword
                s0 << r9
              end
            end
          end
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(NullCondition1)
        r0.extend(NullCondition2)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:null_condition][start_index] = r0

      r0
    end


    class Parser < Treetop::Runtime::CompiledParser
      include Null
    end
  end

  (remove_const(:NullParser) if const_defined?(:NullParser)) rescue nil; NullParser = Null::Parser

end
