# Autogenerated from a Treetop grammar. Edits may be lost.


module OracleSqlParser::Grammar::Expression
  module Datetime
    include Treetop::Runtime

    def root
      @root ||= :datetime_expression
    end

    module DatetimeExpression0
      def at_keyword
        elements[0]
      end

      def local_keyword
        elements[2]
      end
    end

    module DatetimeExpression1
      def at_keyword
        elements[0]
      end

      def datetime_timezone_clause
        elements[2]
      end
    end

    module DatetimeExpression2
      def not_loop_sql_expression
        elements[0]
      end

      def d
        elements[2]
      end
    end

    module DatetimeExpression3
      def ast
        OracleSqlParser::Ast::DatetimeExpression[
          :expr => not_loop_sql_expression.ast,
          :at => d.try(:at_keyword).ast,
          :local => d.try(:local_keyword).ast,
          :timezone => d.try(:datetime_timezone_clause).ast,
        ]
      end
    end

    def _nt_datetime_expression
      start_index = index
      if node_cache[:datetime_expression].has_key?(index)
        cached = node_cache[:datetime_expression][index]
        if cached
          node_cache[:datetime_expression][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_not_loop_sql_expression
      s0 << r1
      if r1
        r3 = _nt_space
        if r3
          r2 = r3
        else
          r2 = instantiate_node(SyntaxNode,input, index...index)
        end
        s0 << r2
        if r2
          i4 = index
          i5, s5 = index, []
          r6 = _nt_at_keyword
          s5 << r6
          if r6
            r8 = _nt_space
            if r8
              r7 = r8
            else
              r7 = instantiate_node(SyntaxNode,input, index...index)
            end
            s5 << r7
            if r7
              r9 = _nt_local_keyword
              s5 << r9
            end
          end
          if s5.last
            r5 = instantiate_node(SyntaxNode,input, i5...index, s5)
            r5.extend(DatetimeExpression0)
          else
            @index = i5
            r5 = nil
          end
          if r5
            r5 = SyntaxNode.new(input, (index-1)...index) if r5 == true
            r4 = r5
          else
            i10, s10 = index, []
            r11 = _nt_at_keyword
            s10 << r11
            if r11
              r13 = _nt_space
              if r13
                r12 = r13
              else
                r12 = instantiate_node(SyntaxNode,input, index...index)
              end
              s10 << r12
              if r12
                r14 = _nt_datetime_timezone_clause
                s10 << r14
              end
            end
            if s10.last
              r10 = instantiate_node(SyntaxNode,input, i10...index, s10)
              r10.extend(DatetimeExpression1)
            else
              @index = i10
              r10 = nil
            end
            if r10
              r10 = SyntaxNode.new(input, (index-1)...index) if r10 == true
              r4 = r10
            else
              @index = i4
              r4 = nil
            end
          end
          s0 << r4
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(DatetimeExpression2)
        r0.extend(DatetimeExpression3)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:datetime_expression][start_index] = r0

      r0
    end

    module DatetimeTimezoneClause0
      def time_keyword
        elements[0]
      end

      def zone_keyword
        elements[2]
      end

      def expr
        elements[4]
      end
    end

    module DatetimeTimezoneClause1
      def ast
        OracleSqlParser::Ast::TimezoneClause[
          :time => time_keyword.ast,
          :zone => zone_keyword.ast,
          :expr => expr.ast,
        ]
      end
    end

    def _nt_datetime_timezone_clause
      start_index = index
      if node_cache[:datetime_timezone_clause].has_key?(index)
        cached = node_cache[:datetime_timezone_clause][index]
        if cached
          node_cache[:datetime_timezone_clause][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_time_keyword
      s0 << r1
      if r1
        r3 = _nt_space
        if r3
          r2 = r3
        else
          r2 = instantiate_node(SyntaxNode,input, index...index)
        end
        s0 << r2
        if r2
          r4 = _nt_zone_keyword
          s0 << r4
          if r4
            r6 = _nt_space
            if r6
              r5 = r6
            else
              r5 = instantiate_node(SyntaxNode,input, index...index)
            end
            s0 << r5
            if r5
              i7 = index
              r8 = _nt_text_literal
              if r8
                r8 = SyntaxNode.new(input, (index-1)...index) if r8 == true
                r7 = r8
              else
                r9 = _nt_dbtimezone_keyword
                if r9
                  r9 = SyntaxNode.new(input, (index-1)...index) if r9 == true
                  r7 = r9
                else
                  r10 = _nt_sessiontimezone_keyword
                  if r10
                    r10 = SyntaxNode.new(input, (index-1)...index) if r10 == true
                    r7 = r10
                  else
                    r11 = _nt_expr
                    if r11
                      r11 = SyntaxNode.new(input, (index-1)...index) if r11 == true
                      r7 = r11
                    else
                      @index = i7
                      r7 = nil
                    end
                  end
                end
              end
              s0 << r7
            end
          end
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(DatetimeTimezoneClause0)
        r0.extend(DatetimeTimezoneClause1)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:datetime_timezone_clause][start_index] = r0

      r0
    end


    class Parser < Treetop::Runtime::CompiledParser
      include Datetime
    end
  end

  (remove_const(:DatetimeParser) if const_defined?(:DatetimeParser)) rescue nil; DatetimeParser = Datetime::Parser

end
